config/routes.rb
Rails.application.routes.draw do
  # Google mapのテスト用ルーティング
  get 'maps/index'

  # 管理者側
  scope module: :admin do
    devise_for :admins
    get "/admin" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # ユーザー側
  scope module: :public do
    # ユーザー登録
    devise_for :users

    # トップ・アバウト画面
    get "/" => "homes#top"
    get "/about" => "homes#about"

    # 執筆者
    resources :writers, except: [:new, :create, :destroy] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end

    # 執筆
    resources :writings

    # 構造物
    resources :structures, except: [:new, :create]

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/designer.rb
class Designer < ApplicationRecord
  # 構造物テーブルとのアソシエーション
  # belongs_to :structure

  # バリデーション
  validates :last_name, presence: true



end

app/models/genre.rb
class Genre < ApplicationRecord
  # 構造物テーブルとのアソシエーション
  has_many :structures, dependent: :destroy
  accepts_nested_attributes_for :structures

  # バリデーション
  validates :name, presence: true

end

app/models/introduction.rb
class Introduction < ApplicationRecord
  # 構造物テーブルとのアソシエーション
  # belongs_to :structure


end

app/models/photo.rb
class Photo < ApplicationRecord
  # 構造物テーブルとのアソシエーション
  # belongs_to :structure

  # 画像アップ用メソッド
  # attachment :image
end

app/models/structure.rb
class Structure < ApplicationRecord
  # `ユーザーテーブルとのアソシエーション
  has_many :structure_users, dependent: :destroy
  has_many :users, through: :structure_users
  accepts_nested_attributes_for :structure_users

  # 設計者テーブルとのアソシエーション
  # has_many :designers, dependent: :destroy
  # accepts_nested_attributes_for :designers

  # 写真テーブルとのアソシエーション
  # has_many :photos, dependent: :destroy
  # accepts_nested_attributes_for :photos

  # 説明文テーブルとのアソシエーション
  # has_many :introductions, dependent: :destroy
  # accepts_nested_attributes_for :introductions

  # タグテーブルとのアソシエーション
  has_many :structure_tags, dependent: :destroy
  has_many :tags, through: :structure_tags
  accepts_nested_attributes_for :structure_tags

  # ジャンルテーブルとのアソシエーション
  belongs_to :genre

  # 画像アップ用メソッド
  attachment :image

  # バリデーション
  validates :name, presence: true

  # 所在地関連カラムを結合
  def structure_address
    [prefecture, city, address].compact.join(', ')
  end
  # オブジェクトの所在地をジオコーダーに指示
  geocoded_by :structure_address
  # コールバックを介して呼び出せるジオコードメソッドを追加
  after_validation :geocode, if: :address_changed?

end

app/models/structure_tag.rb
class StructureTag < ApplicationRecord
  # 構造物テーブルとのアソシエーション
  belongs_to :structure

  # タグテーブルとのアソシエーション
  belongs_to :tag

end

app/models/structure_user.rb
class StructureUser < ApplicationRecord
  # ユーザーテーブルとのアソシエーション
  belongs_to :user

  # 構造物テーブルとのアソシエーション
  belongs_to :structure

end

app/models/tag.rb
class Tag < ApplicationRecord
  # 構造物テーブルとのアソシエーション
  has_many :structure_tags, dependent: :destroy
  has_many :structures, through: :structure_tags
  # accepts_nested_attributes_for :structure_tags, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image

  # 構造物テーブルとのアソシエーション
  has_many :structure_users, dependent: :destroy
  has_many :structures, through: :structure_users

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
# 管理者側homesコントローラー

  def top
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/helpers/writings_helper.rb
module WritingsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StructureDictionary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark text-white">
      <a class="navbar-brand" href="/">Structure dictionary</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#barmenu" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="navbar-collapse" id="barmenu">
          <ul class="navbar-nav ml-auto align-items-center">
          <!--管理者としてログインした場合のヘッダー-->
          <% if admin_signed_in? %>
            <!--<li class="nav-item"><%#=link_to "執筆者一覧", class: "nav-link"  %></li>-->
            <li class="nav-item"><%=link_to "ジャンル一覧", genres_path, class: "nav-link"  %></li>
            <li class="nav-item"><%=link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link"  %></li>

          <!--会員としてログインした場合のヘッダー-->
          <% elsif user_signed_in? %>
            <span>ようこそ、<%= current_user.name %>さん！</span>
            <li class="nav-item"><%=link_to "About", about_path, class: "nav-link" %></li>
            <!--<li><%#=link_to "設計者一覧" %></li>-->
            <!--<li><%#=link_to "所在地一覧" %></li>-->
            <!--<li><%#=link_to "執筆者一覧", writers_path %></li>-->
            <li class="nav-item"><%=link_to "執筆" , new_writing_path, class: "nav-link" %></li>
            <li class="nav-item"><%=link_to "マイページ", writer_path(current_user.id), class: "nav-link" %></li>
            <li class="nav-item"><%=link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%=link_to "About", about_path, class: "nav-link" %></li>
            <!--<li><%#=link_to "設計者一覧" %></li>-->
            <!--<li><%#=link_to "所在地一覧" %></li>-->
            <!--<li><%#=link_to "執筆者一覧", writers_path %></li>-->
            <li class="nav-item"><%=link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"><%=link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
          </ul>
        </div>
        <% end %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>